name: verifhal9k
version: 0.1.0
extra-source-files:
  - README.md

dependencies:
  - base
  - containers
  - megaparsec
  - mtl
  - optparse-generic
  - text
  - fgl

default-extensions:
  - OverloadedStrings
  - RecordWildCards

library:
  exposed-modules:
    - VerifPal.Types
    - VerifPal.Parser
    - VerifPal.Check
  source-dirs: src

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - verifhal9k
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec
      - hspec-megaparsec
      - file-embed

executables:
  verifairy:
    source-dirs: app
    main: Main.hs
    dependencies:
      - verifhal9k
      - filepath
      - optparse-applicative
      - githash
      - diagnose == 1.8.1